DROP DATABASE IF EXISTS Mantenimiento;
CREATE DATABASE sistema CHARACTER SET utf8mb4 
COLLATE utf8mb4_general_ci;
USE Mantenimiento;

CREATE TABLE usuario(
  iduser INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL,
  apellidoP VARCHAR(20) NOT NULL,
  apellidoM VARCHAR(30) NOT NULL,
  marca VARCHAR(30) NOT NULL,
  modelo VARCHAR(30) NOT NULL,
  numserie VARCHAR(30) NOT NULL,
  numInventario VARCHAR(30) NOT NULL,
  So VARCHAR(30) NOT NULL,
  Procesador VARCHAR(30) NOT NULL,
  DiscoDuro VARCHAR(30) NOT NULL,
  Ram VARCHAR(30) NOT NULL,
  TipoMemoria VARCHAR(30) NOT NULL,
  Observaciones VARCHAR(30) NOT NULL,
  contraseña VARCHAR(30) NOT NULL,
  NEquipo VARCHAR(30) NOT NULL,
  IP VARCHAR(30) NOT NULL,
  Mac VARCHAR(30) NOT NULL,
  );